### ISSUE TITLE
[ON HOLD] Scrub Bike Rack Data

### ISSUE THREAD

**Issue by corinagum** [corinajacobson/bike-route-hawaii#1]
list of bike racks: https://docs.google.com/spreadsheets/d/15NQospgSeinlZ6DVf3GS2shmpnPtKjP_Kjc1yVAPgLg/edit?usp=sharing

locations on google maps: https://www.google.com/maps/d/edit?mid=z1nNzbgVom4o.knOy8HV4b5Qs&usp=sharing

Add coordinates on the data table in column Location. Pasted straight from the URL is fine.

**Comment by corinagum** [comment]
Corina finished bike racks 277-379 on excel sheet.

**Comment by KSalcedo** [comment]
You have the wrong email here. Please remove me from this email list. Thanks :)


-Katherine

**Comment by corinagum** [comment]
On hold due to pivot
