### ISSUE TITLE
Digest Info: Make Data List & Tech Stack List

### ISSUE THREAD

**Issue by kentsalcedo** [corinajacobson/bike-route-hawaii#2]
2 list consisting of highlights you find

**Comment by corinagum** [comment]
Tech Stack : Angular, Ionic, Express, Postgress, Node, Leaflet
One thing to keep in mind is that we must be explicit when asking for permission to access locations on the phone. Requirements: permission must be obtained from the user, the website hostname must be displayed, and it must be possible for the user to revoke permission.
Data : we will need to scrub the bike rack locations and find their geolocations
non-MVP: add bike shop data, which we will have to research
non-MVP: add traffic data, which needs to be scrubbed
