### ISSUE TITLE
Where Am I button

### ISSUE THREAD

**Issue by RizOrt218** [corinajacobson/bike-route-hawaii#4]
create start button (view clickable button)

**Comment by corinagum** [comment]
Geo-locate user

**Comment by KSalcedo** [comment]
You have the wrong email here. Please remove me from this email list. Thanks :)

-Katherine

**Comment by corinagum** [comment]
Hey sorry about that - I got your first email and removed your contact info
but it still looks like you're receiving them. Any advice on what to do? I
haven't found your account in any other areas other than the contributors
section, which is now blank.

Corina Jacobson
