### ISSUE TITLE
Add reporting/suggestions to

### ISSUE THREAD

**Issue by corinagum** [corinajacobson/bike-route-hawaii#47]
the user marker and/or create the ability for user to drag a marker on a point to make a report or suggestion

**Comment by ncadiente** [comment]
added draggable marker, need to show nearest station,  debug, and make it look nicer

**Comment by ncadiente** [comment]
using create a point breaks the done button for gear menue

**Comment by RizOrt218** [comment]
Done button works on IOS; breaks on Android

**Comment by RizOrt218** [comment]
bug fix for done button for both device.
